version: "3.9"

services:
  db:
    image: postgres:15
    container_name: carsharing_db
    environment:
      POSTGRES_DB: carsharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  tests:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: carsharing
      DB_USER: postgres
      DB_PASSWORD: postgres