version: "3.9"

services:
  db:
    image: postgres:16
    container_name: car_rental_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carsharing
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d  # создаёт схему при старте

  app:
    build: .
    container_name: car_rental_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/carsharing
    volumes:
      - ./tests:/app/tests
      - ./sql:/app/sql
    command: pytest -v

volumes:
  db_data: